name: Build
on:
  push:
    branches:
      - "r0.2.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=docker_image::ghcr.io/${{ github.repository }}/advisor:latest
# echo ::set-output name=docker_image::ghcr.io/${{ github.repository }}/master:$(git rev-parse --short=7 ${{ github.sha }})
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag ${{ steps.vars.outputs.docker_image }}
      - name: Login to registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Push docker image
        run: |
          docker push ${{ steps.vars.outputs.docker_image }}
      # - name: Deploy
      #   run: |
      #     jq -n \
      #     --arg msg "$(git log --format=%B -n 1)" \
      #     '{"repository":"${{ github.repository }}","dockerImage":"${{ steps.vars.outputs.docker_image }}","branch":"${{ github.ref }}","commitMessage":$msg}' | \
      #     curl -s --fail -X POST -H 'Content-Type: application/json' -H 'Authorization: Basic ${{ secrets.deployToken }}' -d@- https://galleon.pekle.lv/deploy
